ExpertsProject/Controllers/HomeController.cs
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using IdentitySample.Models;
using System;
using System.Linq;
using PagedList;
using System.Web.Security;

namespace IdentitySample.Controllers
{
    [Authorize]
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private ApplicationDbContext db;
        //
        //
        public HomeController()
        {
            db = new ApplicationDbContext();
        }
              
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var experts = from s in db.Users.Where(s => s.Roles.Select(y => y.RoleId).Contains("d6ee209f-679f-4b49-bbb8-cc83efeefef1"))
                          select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                experts = experts.Where(s => s.lastName.Contains(searchString) || s.firstName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    experts = experts.OrderByDescending(s => s.lastName);
                    break;
                default:
                    experts = experts.OrderBy(s => s.lastName);
                    break;
            }
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(experts.ToPagedList(pageNumber, pageSize));
            
        }
        [Authorize]
        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;


        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public HomeController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
    }
}

ExpertsProject/Controllers/UserAdminController.cs
using IdentitySample.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;

namespace IdentitySample.Controllers
{
    public class UsersAdminController : Controller
    {
        private ApplicationDbContext _dbContext;
        public UsersAdminController()
        {
            _dbContext = new ApplicationDbContext();
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        public async Task<ActionResult> Index(string stringName)
        {
            var experts = from m in _dbContext.Users
                          select m;
            if (!string.IsNullOrEmpty(stringName))
            {
                experts = experts.Where(s => s.register.ToString().Equals(stringName));
            }
            return View(await experts.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = userViewModel.Email,
                    Email = userViewModel.Email,
                    Address = userViewModel.Address,
                    State = userViewModel.State,
                    City = userViewModel.City,
                    PostalCode = userViewModel.PostalCode,
                    register = userViewModel.register,
                    number = userViewModel.number,
                    prefix = userViewModel.prefix,
                    isDeleted = userViewModel.isDeleted,
                    expertise = userViewModel.expertise,
                    expertise2 = userViewModel.expertise2,
                    expertise3 = userViewModel.expertise3
                };
                user.Address = userViewModel.Address;
                user.City = userViewModel.City;
                user.State = userViewModel.State;
                user.PostalCode = userViewModel.PostalCode;
                user.firstName = userViewModel.firstName;
                user.lastName = userViewModel.lastName;
                user.number = userViewModel.number;
                user.register = userViewModel.register;
                user.prefix = userViewModel.prefix;
                user.isDeleted = userViewModel.isDeleted;
                user.expertise3 = userViewModel.expertise3;
                user.expertise2 = userViewModel.expertise2;
                user.expertise = userViewModel.expertise;
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                Address = user.Address,
                City = user.City,
                State = user.State,
                PostalCode = user.PostalCode,
                firstName = user.firstName,
                lastName = user.lastName,
                number = user.number,
                register = user.register,
                prefix = user.prefix,
                isDeleted = user.isDeleted,
                expertise = user.expertise,
                expertise2 = user.expertise2,
                expertise3 = user.expertise3,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id,prefix, Address, City, State,PostalCode,firstName,lastName,number,register, isDeleted, expertise,expertise2,expertise3")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;
                user.Address = editUser.Address;
                user.City = editUser.City;
                user.State = editUser.State;
                user.PostalCode = editUser.PostalCode;
                user.firstName = editUser.firstName;
                user.lastName = editUser.lastName;
                user.number = editUser.number;
                user.register = editUser.register;
                user.prefix = editUser.prefix;
                user.isDeleted = editUser.isDeleted;
                user.expertise3 = editUser.expertise3;
                user.expertise2 = editUser.expertise2;
                user.expertise = editUser.expertise;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                if (User.IsInRole("Admin"))
                {
                    result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                if (User.IsInRole("Admin"))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", new RouteValueDictionary(new { controller = "Home", action = "Index" }));
                }
            }
            ModelState.AddModelError("", "Something failed."); 
            return View();
        }

        //
        // GET: /Users/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //

ExpertsProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<hgroup>
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>
<div class="row-fluid">
    <div class="span12">
        <p>Software Engineering ORCA Fall 2016: Adam Roberts, Ryan Dixon , & Nate Miklas</p>
    </div>
</div>

ExpertsProject/Views/Home/Index.cshtml
@*@model IEnumerable<IdentitySample.Models.ApplicationUser>*@
@model PagedList.IPagedList<IdentitySample.Models.ApplicationUser>
@using Microsoft.AspNet.Identity
@using IdentitySample.Models
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    var manager = new UserManager<ApplicationUser>(new Microsoft.AspNet.Identity.EntityFramework.UserStore<ApplicationUser>(new ApplicationDbContext()));
    var currentUser = manager.FindById(User.Identity.GetUserId());
    ViewBag.Title = "Home Page";
    var user = User.Identity.GetUserName();
}
@using (Html.BeginForm("Index", "Home", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<tr>
    <th>
        @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
    </th>
    <th></th>
</tr>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
<!DOCTYPE html>
<html>
<head>
    <style>
        a {
            color: #079449;
        }

        p {
            padding-top: 5px;
            color: #079449;
        }

        #mydiv .entry-content {
            display: inline-block;
            width: 100%;
            margin: 0 auto;
            float: left;
            padding: 3px;
            padding-left: 8px;
            padding-right: 15px;
        }

        b {
            display: inline-block;
            text-align: left;
            margin: 0 auto;
            width: 100%;
        }

        abc {
        }
    </style>
</head>
@if (Model != null)
{
    foreach (var experts in Model)
    {
        if (experts.register != 0 && experts.isDeleted == 0)
        {
            <body>
                <div id="mydiv">
                    <div class="entry-content" style="width:485px;">
                        <div class="row" style="width:485px;">
                            <div class="small-12 large-10 columns border-r" role="main" style="width:485px;">
                                <article class="post-/ page type-page status-publish hentry" style="width:485px;">
                                    <div class="entry-content" style="width:485px;">
                                        <div style="position: absolute; top:0; right:0;"></div>
                                        <div class="cn-list" data-connections-version="8.5.26-0.1.9" style="width:485px;">
                                            <div class="cn-template cn-card" data-template-version="3.0" style="width:485px;">
                                                <div class="connections-list cn-list-body cn-clear">
                                                    <div class="cn-list-secion-head"></div>
                                                    <div class="cn-list-row-alternate vcard individual"
                                                         data-entry-type="Individual"
                                                         data-entry-slug="name" style="width:485px;">
                                                        <div class="cn-entry" id="div11" style="background-color: #FFF; width: 485px; height: 100px; border: 1px solid #E3E3E3; border-radius: 4px; color: #000; margin: 8px 0; padding: 10px; position: relative">
                                                            <div class="cn-left" style="width:45%; float:left">
                                                                <div style="clear:both;"></div>
                                                                <div style="margin-bottom: 10px;">
                                                                    <div style="font-size:larger;font-variant: small-caps">
                                                                        <strong>
                                                                            <a href="@Url.Action("Index", "Messages", new { id = User.Identity.GetUserId() }, null)" style="color:#079449" title="@experts.prefix + @experts.firstName + @experts.lastName">
                                                                                <span class="fn n notranslate">
                                                                                    <span class="given-name">@experts.prefix  @experts.firstName</span>
                                                                                    <span class="family-name">@experts.lastName</span>
                                                                                </span>
                                                                            </a>
                                                                        </strong>
                                                                    </div>
                                                                    <span class="org">
                                                                        <span class="organization-name notranslate">Marshall University</span>
                                                                    </span>
                                                                </div>
                                                            </div>
                                                            <div class="cn-right" style="text-align: left;">
                                                                <div class="phone-number-block">
                                                                    <span class="tel cn-phone-number">
                                                                        <span class="phone-name">Work Phone</span>
                                                                        <span class="cn-separator">:</span>
                                                                        <span class="value"> @if (experts.number != null) {@String.Format("{0:(###) ###-####}", double.Parse(experts.number))}</span>
                                                                        <span class="type" style="display: none;"> work</span>
                                                                    </span>
                                                                </div>
                                                                <div class="email-address-block">
                                                                    <div class="email cn-email-address">
                                                                        <span class="email-name">Work Email</span>
                                                                        <span class="cn-separator">:</span>
                                                                        <span class="email-address">
                                                                            <a class="value" title="@experts.prefix @experts.firstName @experts.lastName work email." style="color:#079449" href="mailto: @experts.Email ">@experts.Email</a>
                                                                        </span>
                                                                        <span class="type" style="display: none;">INTERNET</span>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div style="clear:both"></div>
                                                            <div class="cn-meta" style="margin-top: 4px"></div>
                                                            <div class="cn-clear" style="display:table; width:100%;">
                                                                <div style="display:table-cell; vertical-align:middle;">
                                                                    <div class="cn-categories">
                                                                        <span class="cn_category_label">Expert In:</span>
                                                                        <span class="cn-category-name cn_category cn-category-12" style="font-variant:small-caps;"> @experts.expertise @experts.expertise2 @experts.expertise3</span>
                                                                    </div>
                                                                </div>
                                                                <div style="display:table-cell; text-align:right;vertical-align:middle;">
                                                                    <span class="cn-last-updated" style="font-size: 10px; font-variant: small-caps; margin-right: 10px; display:none">Updated 5 years ago.</span>
                                                                    <span class="cn-return-to-top">
                                                                        @if (user != null && currentUser.Email == experts.Email)
                                                                        {
                                                                            @Html.ActionLink("Remove", "Edit", "UsersAdmin", new { id = User.Identity.GetUserId(), @class = "abc" }, null)
                                                                        }
                                                                    </span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                            </div>
                        </div>
                    </div>
                </div>
            </body>
        }
    }
}
</html>